### ISSUE TITLE
`gem push` doesn't work without an existing api key

### ISSUE THREAD

**Issue by kejadlen** [geminabox/geminabox#153]
Trying to `gem push` to a `geminabox` host without an existing api key results in a prompt for an email and password, which then fails to work.

``` shell
❯ gem push pkg/[GEM].gem --host [HOST]
Enter your [HOST] credentials.
Don't have an account yet? Create one at [HOST]/sign_up
   Email:
Password:

ERROR:  While executing gem ... (NoMethodError)
    undefined method `request_uri' for #<URI::Generic:0x007fe759a55e18>
```

**Comment by coryallegory** [comment]
Creating a credentials file skips over the prompt for credentials, but the same ERROR: while executing gem... message is returned for me.
Mine is slightly different, `undefined method 'downcase' for nil:NilClass`

Server is running ruby 1.9.3p551
WinServer2012x64
geminabox 0.12.4

Client calling `gem push a.gem -- host site.com` is running ruby 2.1.7p400
Win7x64

**Comment by coryallegory** [comment]
I presume downcase is attempting to be called on an email variable, which I would not have provided. Not sure which library would be to blame for this under the hood?

**Comment by robertely** [comment]
This may not have gotten any comments in a while but is still absolutely an issue.

*Steps to reproduce:*
```
test-pacakges rob$ cat ~/.gem/credentials
---
:rubygems_api_key: 'missing'
```

```
test-pacakges rob$ gem push --host gems.company.net cool-cool-test-package-1.0.1.gem
Pushing gem to gems.company.net...
ERROR:  While executing gem ... (NoMethodError)
    undefined method `downcase' for nil:NilClass
```

**Comment by ariera** [comment]
the `~/.gem/credentials` trick worked for me.

geminabox server is running `0.13.5`
ruby version that i use to run `gem push` is `ruby 2.3.3p222 (2016-11-21 revision 56859)` and it also worked with `ruby 2.0.0p648 (2015-12-16 revision 53162)`

**Comment by ShamoX** [comment]
Hi,

Only to say that I had the same error and it was just because I forgot to put the protocol at the beginning of the host URL.

I investigated a little in the code and found that this is caused by `URI.parse` in gem cutter_utilisites.rb:74. Here is the stack of the error then (generated in a gitlab-ci docker environment) :

```ruby
Exception `NoMethodError' at /usr/local/lib/ruby/2.5.0/rubygems/request/connection_pools.rb:54 - undefined method `downcase' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `downcase' for nil:NilClass
	/usr/local/lib/ruby/2.5.0/rubygems/request/connection_pools.rb:54:in `no_proxy?'
	/usr/local/lib/ruby/2.5.0/rubygems/request/connection_pools.rb:80:in `net_http_args'
	/usr/local/lib/ruby/2.5.0/rubygems/request/connection_pools.rb:20:in `pool_for'
	/usr/local/lib/ruby/2.5.0/rubygems/remote_fetcher.rb:364:in `request'
	/usr/local/lib/ruby/2.5.0/rubygems/gemcutter_utilities.rb:86:in `rubygems_api_request'
	/usr/local/lib/ruby/2.5.0/rubygems/commands/push_command.rb:93:in `send_gem'
	/usr/local/lib/ruby/2.5.0/rubygems/commands/push_command.rb:49:in `execute'
	/usr/local/lib/ruby/2.5.0/rubygems/command.rb:313:in `invoke_with_build_args'
	/usr/local/lib/ruby/2.5.0/rubygems/command_manager.rb:171:in `process_args'
	/usr/local/lib/ruby/2.5.0/rubygems/command_manager.rb:141:in `run'
	/usr/local/lib/ruby/2.5.0/rubygems/gem_runner.rb:59:in `run'
	/usr/local/bin/gem:21:in `<main>'
```

The error could simply be more explicit to allow users not to create an issue for that :)

Hope it will help users like me ;)
